name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files (debug)
      run: ls -ltra

    - name: Find script file (debug)
      run: find . -name "ascii-script.sh"

    - name: Run ascii-script.sh
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh
