name: Generate ASCII Artwork

on:
  push

jobs:
   ascii_job:
     runs-on: ubuntu-latest
     steps:

     - name: Checkout Repo
       uses: actions/checkout@V4

     - name: List Files
       run: ls -ltra

     - name: Executing Shell Script
       run: |
         chmod +x ascii-script.sh
         ./ascii-script.sh